version: '3.8'

services:
  # PHP/Laravel Application Service
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: otonometer_cms_app
    restart: unless-stopped
    working_dir: /var/www
    mem_limit: 2g # Set memory limit to 2GB
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini # Custom PHP config
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf   # Custom FPM config
    networks:
      - laravel

  # Nginx Web Server Service
  nginx:
    image: nginx:alpine
    container_name: otonometer_cms_nginx
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

# Docker Networks
networks:
  laravel:
    driver: bridge

# Named Volume for Database Persistence
volumes:
  db_data:
    driver: local