apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: otonometer-webcore-storage-stag
  name: otonometer-webcore-storage-stag
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
status: {}
